#!/usr/bin/env tsx
// scripts/seed.ts
// Nuke Tracker — Complete Database Seed
// All 30 MLB stadiums, teams, and baseline park factors

import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

// ─── Stadium Data ─────────────────────────────────────────────────────────────
// Sources: Baseball Reference, Statcast park factors (2021-2025 avg)
// HR Factor > 1.00 = HR-friendly, < 1.00 = pitcher-friendly

const STADIUMS = [
  {
    id: 'yankee-stadium',
    name: 'Yankee Stadium',
    city: 'New York', state: 'NY',
    latitude: 40.8296, longitude: -73.9262,
    altitude: 55,
    capacity: 46537,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 318, leftCenter: 399, centerField: 408, rightCenter: 385, rightField: 314,
    parkFactor: 1.032, hrFactor: 1.138, lhHrFactor: 1.284, rhHrFactor: 1.024,
  },
  {
    id: 'fenway-park',
    name: 'Fenway Park',
    city: 'Boston', state: 'MA',
    latitude: 42.3467, longitude: -71.0972,
    altitude: 20,
    capacity: 37755,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 310, leftCenter: 379, centerField: 420, rightCenter: 380, rightField: 302,
    parkFactor: 1.018, hrFactor: 1.058, lhHrFactor: 0.891, rhHrFactor: 1.142,
  },
  {
    id: 'camden-yards',
    name: 'Oriole Park at Camden Yards',
    city: 'Baltimore', state: 'MD',
    latitude: 39.2839, longitude: -76.6218,
    altitude: 43,
    capacity: 45971,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 337, leftCenter: 364, centerField: 400, rightCenter: 373, rightField: 320,
    parkFactor: 1.024, hrFactor: 1.097, lhHrFactor: 1.112, rhHrFactor: 1.089,
  },
  {
    id: 'rogers-centre',
    name: 'Rogers Centre',
    city: 'Toronto', state: 'ON',
    latitude: 43.6414, longitude: -79.3894,
    altitude: 76,
    capacity: 49282,
    roofType: 'RETRACTABLE',
    surface: 'Artificial',
    leftField: 328, leftCenter: 375, centerField: 400, rightCenter: 375, rightField: 328,
    parkFactor: 1.008, hrFactor: 1.042, lhHrFactor: 1.038, rhHrFactor: 1.045,
  },
  {
    id: 'tropicana-field',
    name: 'Tropicana Field',
    city: 'St. Petersburg', state: 'FL',
    latitude: 27.7683, longitude: -82.6534,
    altitude: 9,
    capacity: 25000,
    roofType: 'FIXED_DOME',
    surface: 'Artificial',
    leftField: 315, leftCenter: 370, centerField: 404, rightCenter: 370, rightField: 322,
    parkFactor: 0.961, hrFactor: 0.914, lhHrFactor: 0.923, rhHrFactor: 0.908,
  },
  {
    id: 'guaranteed-rate-field',
    name: 'Guaranteed Rate Field',
    city: 'Chicago', state: 'IL',
    latitude: 41.8300, longitude: -87.6338,
    altitude: 595,
    capacity: 40615,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 330, leftCenter: 377, centerField: 400, rightCenter: 372, rightField: 335,
    parkFactor: 1.041, hrFactor: 1.121, lhHrFactor: 1.108, rhHrFactor: 1.131,
  },
  {
    id: 'progressive-field',
    name: 'Progressive Field',
    city: 'Cleveland', state: 'OH',
    latitude: 41.4962, longitude: -81.6852,
    altitude: 653,
    capacity: 34788,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 325, leftCenter: 370, centerField: 405, rightCenter: 375, rightField: 325,
    parkFactor: 0.978, hrFactor: 0.952, lhHrFactor: 0.961, rhHrFactor: 0.946,
  },
  {
    id: 'comerica-park',
    name: 'Comerica Park',
    city: 'Detroit', state: 'MI',
    latitude: 42.3390, longitude: -83.0485,
    altitude: 600,
    capacity: 41083,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 345, leftCenter: 370, centerField: 420, rightCenter: 365, rightField: 330,
    parkFactor: 0.956, hrFactor: 0.891, lhHrFactor: 0.878, rhHrFactor: 0.901,
  },
  {
    id: 'kauffman-stadium',
    name: 'Kauffman Stadium',
    city: 'Kansas City', state: 'MO',
    latitude: 39.0517, longitude: -94.4803,
    altitude: 973,
    capacity: 37903,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 330, leftCenter: 375, centerField: 410, rightCenter: 375, rightField: 330,
    parkFactor: 0.988, hrFactor: 0.971, lhHrFactor: 0.968, rhHrFactor: 0.974,
  },
  {
    id: 'target-field',
    name: 'Target Field',
    city: 'Minneapolis', state: 'MN',
    latitude: 44.9817, longitude: -93.2781,
    altitude: 841,
    capacity: 38544,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 339, leftCenter: 377, centerField: 404, rightCenter: 367, rightField: 328,
    parkFactor: 0.984, hrFactor: 0.963, lhHrFactor: 0.971, rhHrFactor: 0.957,
  },
  {
    id: 'minute-maid-park',
    name: 'Minute Maid Park',
    city: 'Houston', state: 'TX',
    latitude: 29.7573, longitude: -95.3555,
    altitude: 40,
    capacity: 41168,
    roofType: 'RETRACTABLE',
    surface: 'Grass',
    leftField: 315, leftCenter: 362, centerField: 435, rightCenter: 373, rightField: 326,
    parkFactor: 1.012, hrFactor: 1.048, lhHrFactor: 1.142, rhHrFactor: 0.982,
  },
  {
    id: 'angel-stadium',
    name: 'Angel Stadium',
    city: 'Anaheim', state: 'CA',
    latitude: 33.8003, longitude: -117.8827,
    altitude: 160,
    capacity: 45517,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 347, leftCenter: 390, centerField: 396, rightCenter: 370, rightField: 350,
    parkFactor: 0.991, hrFactor: 0.978, lhHrFactor: 0.984, rhHrFactor: 0.973,
  },
  {
    id: 'oakland-coliseum',
    name: 'Oakland Coliseum',
    city: 'Oakland', state: 'CA',
    latitude: 37.7516, longitude: -122.2005,
    altitude: 23,
    capacity: 46847,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 330, leftCenter: 388, centerField: 400, rightCenter: 362, rightField: 330,
    parkFactor: 0.944, hrFactor: 0.887, lhHrFactor: 0.879, rhHrFactor: 0.893,
  },
  {
    id: 'safeco-field',
    name: 'T-Mobile Park',
    city: 'Seattle', state: 'WA',
    latitude: 47.5914, longitude: -122.3325,
    altitude: 23,
    capacity: 47929,
    roofType: 'RETRACTABLE',
    surface: 'Grass',
    leftField: 331, leftCenter: 378, centerField: 401, rightCenter: 381, rightField: 326,
    parkFactor: 0.963, hrFactor: 0.921, lhHrFactor: 0.908, rhHrFactor: 0.931,
  },
  {
    id: 'globe-life-field',
    name: 'Globe Life Field',
    city: 'Arlington', state: 'TX',
    latitude: 32.7473, longitude: -97.0845,
    altitude: 571,
    capacity: 40518,
    roofType: 'RETRACTABLE',
    surface: 'Artificial',
    leftField: 329, leftCenter: 372, centerField: 407, rightCenter: 374, rightField: 326,
    parkFactor: 1.021, hrFactor: 1.072, lhHrFactor: 1.064, rhHrFactor: 1.078,
  },
  {
    id: 'dodger-stadium',
    name: 'Dodger Stadium',
    city: 'Los Angeles', state: 'CA',
    latitude: 34.0739, longitude: -118.2400,
    altitude: 515,
    capacity: 56000,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 330, leftCenter: 375, centerField: 395, rightCenter: 375, rightField: 330,
    parkFactor: 0.984, hrFactor: 0.957, lhHrFactor: 0.949, rhHrFactor: 0.963,
  },
  {
    id: 'oracle-park',
    name: 'Oracle Park',
    city: 'San Francisco', state: 'CA',
    latitude: 37.7786, longitude: -122.3893,
    altitude: 10,
    capacity: 41915,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 339, leftCenter: 364, centerField: 399, rightCenter: 421, rightField: 309,
    parkFactor: 0.933, hrFactor: 0.812, lhHrFactor: 0.791, rhHrFactor: 0.828,
  },
  {
    id: 'petco-park',
    name: 'Petco Park',
    city: 'San Diego', state: 'CA',
    latitude: 32.7076, longitude: -117.1570,
    altitude: 62,
    capacity: 40162,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 334, leftCenter: 367, centerField: 396, rightCenter: 391, rightField: 322,
    parkFactor: 0.947, hrFactor: 0.893, lhHrFactor: 0.881, rhHrFactor: 0.902,
  },
  {
    id: 'chase-field',
    name: 'Chase Field',
    city: 'Phoenix', state: 'AZ',
    latitude: 33.4453, longitude: -112.0667,
    altitude: 1082,
    capacity: 48519,
    roofType: 'RETRACTABLE',
    surface: 'Grass',
    leftField: 330, leftCenter: 376, centerField: 407, rightCenter: 376, rightField: 335,
    parkFactor: 1.052, hrFactor: 1.108, lhHrFactor: 1.121, rhHrFactor: 1.098,
  },
  {
    id: 'coors-field',
    name: 'Coors Field',
    city: 'Denver', state: 'CO',
    latitude: 39.7559, longitude: -104.9942,
    altitude: 5200,
    capacity: 50398,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 347, leftCenter: 390, centerField: 415, rightCenter: 375, rightField: 350,
    parkFactor: 1.182, hrFactor: 1.342, lhHrFactor: 1.381, rhHrFactor: 1.314,
  },
  {
    id: 'wrigley-field',
    name: 'Wrigley Field',
    city: 'Chicago', state: 'IL',
    latitude: 41.9484, longitude: -87.6553,
    altitude: 595,
    capacity: 41649,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 355, leftCenter: 368, centerField: 400, rightCenter: 368, rightField: 353,
    parkFactor: 1.028, hrFactor: 1.092, lhHrFactor: 1.108, rhHrFactor: 1.079,
  },
  {
    id: 'great-american-ballpark',
    name: 'Great American Ball Park',
    city: 'Cincinnati', state: 'OH',
    latitude: 39.0975, longitude: -84.5082,
    altitude: 490,
    capacity: 42319,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 328, leftCenter: 370, centerField: 404, rightCenter: 370, rightField: 325,
    parkFactor: 1.067, hrFactor: 1.162, lhHrFactor: 1.148, rhHrFactor: 1.173,
  },
  {
    id: 'american-family-field',
    name: 'American Family Field',
    city: 'Milwaukee', state: 'WI',
    latitude: 43.0282, longitude: -87.9712,
    altitude: 635,
    capacity: 41900,
    roofType: 'RETRACTABLE',
    surface: 'Grass',
    leftField: 344, leftCenter: 371, centerField: 400, rightCenter: 374, rightField: 345,
    parkFactor: 1.019, hrFactor: 1.061, lhHrFactor: 1.072, rhHrFactor: 1.053,
  },
  {
    id: 'pnc-park',
    name: 'PNC Park',
    city: 'Pittsburgh', state: 'PA',
    latitude: 40.4469, longitude: -80.0057,
    altitude: 730,
    capacity: 38362,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 325, leftCenter: 383, centerField: 399, rightCenter: 375, rightField: 320,
    parkFactor: 0.976, hrFactor: 0.944, lhHrFactor: 0.938, rhHrFactor: 0.949,
  },
  {
    id: 'busch-stadium',
    name: 'Busch Stadium',
    city: 'St. Louis', state: 'MO',
    latitude: 38.6226, longitude: -90.1928,
    altitude: 465,
    capacity: 44383,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 336, leftCenter: 375, centerField: 400, rightCenter: 375, rightField: 335,
    parkFactor: 0.974, hrFactor: 0.938, lhHrFactor: 0.932, rhHrFactor: 0.942,
  },
  {
    id: 'citizens-bank-park',
    name: 'Citizens Bank Park',
    city: 'Philadelphia', state: 'PA',
    latitude: 39.9061, longitude: -75.1665,
    altitude: 20,
    capacity: 42901,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 329, leftCenter: 369, centerField: 401, rightCenter: 369, rightField: 330,
    parkFactor: 1.044, hrFactor: 1.118, lhHrFactor: 1.124, rhHrFactor: 1.114,
  },
  {
    id: 'citi-field',
    name: 'Citi Field',
    city: 'New York', state: 'NY',
    latitude: 40.7571, longitude: -73.8458,
    altitude: 20,
    capacity: 41922,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 335, leftCenter: 358, centerField: 408, rightCenter: 375, rightField: 330,
    parkFactor: 0.969, hrFactor: 0.928, lhHrFactor: 0.921, rhHrFactor: 0.933,
  },
  {
    id: 'nationals-park',
    name: 'Nationals Park',
    city: 'Washington', state: 'DC',
    latitude: 38.8730, longitude: -77.0074,
    altitude: 25,
    capacity: 41339,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 336, leftCenter: 377, centerField: 402, rightCenter: 370, rightField: 335,
    parkFactor: 0.998, hrFactor: 1.008, lhHrFactor: 1.012, rhHrFactor: 1.005,
  },
  {
    id: 'truist-park',
    name: 'Truist Park',
    city: 'Atlanta', state: 'GA',
    latitude: 33.8908, longitude: -84.4677,
    altitude: 1050,
    capacity: 41084,
    roofType: 'OPEN',
    surface: 'Grass',
    leftField: 335, leftCenter: 380, centerField: 400, rightCenter: 375, rightField: 325,
    parkFactor: 1.038, hrFactor: 1.104, lhHrFactor: 1.118, rhHrFactor: 1.094,
  },
  {
    id: 'loanDepot-park',
    name: 'loanDepot park',
    city: 'Miami', state: 'FL',
    latitude: 25.7781, longitude: -80.2196,
    altitude: 8,
    capacity: 36742,
    roofType: 'RETRACTABLE',
    surface: 'Grass',
    leftField: 344, leftCenter: 386, centerField: 407, rightCenter: 392, rightField: 335,
    parkFactor: 0.941, hrFactor: 0.881, lhHrFactor: 0.874, rhHrFactor: 0.887,
  },
]

// ─── Team Data ────────────────────────────────────────────────────────────────

const TEAMS = [
  { id: '147', name: 'New York Yankees',    abbreviation: 'NYY', city: 'New York',      division: 'AL East',    league: 'AL', stadiumId: 'yankee-stadium' },
  { id: '111', name: 'Boston Red Sox',      abbreviation: 'BOS', city: 'Boston',        division: 'AL East',    league: 'AL', stadiumId: 'fenway-park' },
  { id: '110', name: 'Baltimore Orioles',   abbreviation: 'BAL', city: 'Baltimore',     division: 'AL East',    league: 'AL', stadiumId: 'camden-yards' },
  { id: '141', name: 'Toronto Blue Jays',   abbreviation: 'TOR', city: 'Toronto',       division: 'AL East',    league: 'AL', stadiumId: 'rogers-centre' },
  { id: '139', name: 'Tampa Bay Rays',      abbreviation: 'TB',  city: 'Tampa Bay',     division: 'AL East',    league: 'AL', stadiumId: 'tropicana-field' },
  { id: '145', name: 'Chicago White Sox',   abbreviation: 'CWS', city: 'Chicago',       division: 'AL Central', league: 'AL', stadiumId: 'guaranteed-rate-field' },
  { id: '114', name: 'Cleveland Guardians', abbreviation: 'CLE', city: 'Cleveland',     division: 'AL Central', league: 'AL', stadiumId: 'progressive-field' },
  { id: '116', name: 'Detroit Tigers',      abbreviation: 'DET', city: 'Detroit',       division: 'AL Central', league: 'AL', stadiumId: 'comerica-park' },
  { id: '118', name: 'Kansas City Royals',  abbreviation: 'KC',  city: 'Kansas City',   division: 'AL Central', league: 'AL', stadiumId: 'kauffman-stadium' },
  { id: '142', name: 'Minnesota Twins',     abbreviation: 'MIN', city: 'Minneapolis',   division: 'AL Central', league: 'AL', stadiumId: 'target-field' },
  { id: '117', name: 'Houston Astros',      abbreviation: 'HOU', city: 'Houston',       division: 'AL West',    league: 'AL', stadiumId: 'minute-maid-park' },
  { id: '108', name: 'Los Angeles Angels',  abbreviation: 'LAA', city: 'Anaheim',       division: 'AL West',    league: 'AL', stadiumId: 'angel-stadium' },
  { id: '133', name: 'Oakland Athletics',   abbreviation: 'OAK', city: 'Oakland',       division: 'AL West',    league: 'AL', stadiumId: 'oakland-coliseum' },
  { id: '136', name: 'Seattle Mariners',    abbreviation: 'SEA', city: 'Seattle',       division: 'AL West',    league: 'AL', stadiumId: 'safeco-field' },
  { id: '140', name: 'Texas Rangers',       abbreviation: 'TEX', city: 'Arlington',     division: 'AL West',    league: 'AL', stadiumId: 'globe-life-field' },
  { id: '119', name: 'Los Angeles Dodgers', abbreviation: 'LAD', city: 'Los Angeles',   division: 'NL West',    league: 'NL', stadiumId: 'dodger-stadium' },
  { id: '137', name: 'San Francisco Giants',abbreviation: 'SF',  city: 'San Francisco', division: 'NL West',    league: 'NL', stadiumId: 'oracle-park' },
  { id: '135', name: 'San Diego Padres',    abbreviation: 'SD',  city: 'San Diego',     division: 'NL West',    league: 'NL', stadiumId: 'petco-park' },
  { id: '109', name: 'Arizona Diamondbacks',abbreviation: 'ARI', city: 'Phoenix',       division: 'NL West',    league: 'NL', stadiumId: 'chase-field' },
  { id: '115', name: 'Colorado Rockies',    abbreviation: 'COL', city: 'Denver',        division: 'NL West',    league: 'NL', stadiumId: 'coors-field' },
  { id: '112', name: 'Chicago Cubs',        abbreviation: 'CHC', city: 'Chicago',       division: 'NL Central', league: 'NL', stadiumId: 'wrigley-field' },
  { id: '113', name: 'Cincinnati Reds',     abbreviation: 'CIN', city: 'Cincinnati',    division: 'NL Central', league: 'NL', stadiumId: 'great-american-ballpark' },
  { id: '158', name: 'Milwaukee Brewers',   abbreviation: 'MIL', city: 'Milwaukee',     division: 'NL Central', league: 'NL', stadiumId: 'american-family-field' },
  { id: '134', name: 'Pittsburgh Pirates',  abbreviation: 'PIT', city: 'Pittsburgh',    division: 'NL Central', league: 'NL', stadiumId: 'pnc-park' },
  { id: '138', name: 'St. Louis Cardinals', abbreviation: 'STL', city: 'St. Louis',     division: 'NL Central', league: 'NL', stadiumId: 'busch-stadium' },
  { id: '143', name: 'Philadelphia Phillies',abbreviation:'PHI', city: 'Philadelphia',  division: 'NL East',    league: 'NL', stadiumId: 'citizens-bank-park' },
  { id: '121', name: 'New York Mets',       abbreviation: 'NYM', city: 'New York',      division: 'NL East',    league: 'NL', stadiumId: 'citi-field' },
  { id: '120', name: 'Washington Nationals',abbreviation: 'WSH', city: 'Washington',    division: 'NL East',    league: 'NL', stadiumId: 'nationals-park' },
  { id: '144', name: 'Atlanta Braves',      abbreviation: 'ATL', city: 'Atlanta',       division: 'NL East',    league: 'NL', stadiumId: 'truist-park' },
  { id: '146', name: 'Miami Marlins',       abbreviation: 'MIA', city: 'Miami',         division: 'NL East',    league: 'NL', stadiumId: 'loanDepot-park' },
]

// ─── Sample Pitchers ──────────────────────────────────────────────────────────

const PITCHERS = [
  { id: 'p-592789', name: 'Gerrit Cole',       firstName: 'Gerrit',  lastName: 'Cole',       throws: 'RIGHT', teamId: '147', era: 2.91, xERA: 3.08, fip: 2.94, whip: 1.01, hr9: 0.9,  flyBallPct: 31.2, hardContactPct: 34.1, barrelPct: 7.2, avgFastball: 96.8, hrVulnScore: 28 },
  { id: 'p-518516', name: 'Chris Sale',         firstName: 'Chris',   lastName: 'Sale',        throws: 'LEFT',  teamId: '144', era: 3.18, xERA: 3.24, fip: 3.11, whip: 1.08, hr9: 0.8,  flyBallPct: 28.4, hardContactPct: 31.2, barrelPct: 6.8, avgFastball: 94.2, hrVulnScore: 24 },
  { id: 'p-605400', name: 'Logan Webb',         firstName: 'Logan',   lastName: 'Webb',         throws: 'RIGHT', teamId: '137', era: 3.25, xERA: 3.41, fip: 3.28, whip: 1.12, hr9: 0.6,  flyBallPct: 24.1, hardContactPct: 28.7, barrelPct: 5.1, avgFastball: 90.4, hrVulnScore: 18 },
  { id: 'p-571578', name: 'Zack Wheeler',       firstName: 'Zack',    lastName: 'Wheeler',      throws: 'RIGHT', teamId: '143', era: 3.07, xERA: 3.19, fip: 3.12, whip: 1.06, hr9: 0.9,  flyBallPct: 34.8, hardContactPct: 36.4, barrelPct: 8.1, avgFastball: 97.2, hrVulnScore: 31 },
  { id: 'p-621111', name: 'Shane Bieber',       firstName: 'Shane',   lastName: 'Bieber',       throws: 'RIGHT', teamId: '114', era: 3.42, xERA: 3.58, fip: 3.45, whip: 1.09, hr9: 1.1,  flyBallPct: 33.2, hardContactPct: 35.8, barrelPct: 8.8, avgFastball: 93.1, hrVulnScore: 38 },
  { id: 'p-656427', name: 'Spencer Strider',    firstName: 'Spencer', lastName: 'Strider',      throws: 'RIGHT', teamId: '144', era: 3.11, xERA: 3.07, fip: 2.98, whip: 1.02, hr9: 0.9,  flyBallPct: 29.8, hardContactPct: 32.1, barrelPct: 7.4, avgFastball: 99.1, hrVulnScore: 26 },
  { id: 'p-663624', name: 'Michael Wacha',      firstName: 'Michael', lastName: 'Wacha',         throws: 'RIGHT', teamId: '111', era: 4.38, xERA: 4.81, fip: 4.52, whip: 1.31, hr9: 1.8,  flyBallPct: 42.1, hardContactPct: 47.8, barrelPct: 14.2, avgFastball: 91.2, hrVulnScore: 91 },
  { id: 'p-641154', name: 'Framber Valdez',     firstName: 'Framber', lastName: 'Valdez',        throws: 'LEFT',  teamId: '117', era: 3.14, xERA: 3.28, fip: 3.21, whip: 1.18, hr9: 0.7,  flyBallPct: 22.4, hardContactPct: 30.1, barrelPct: 5.8, avgFastball: 95.1, hrVulnScore: 22 },
  { id: 'p-669923', name: 'Kodai Senga',        firstName: 'Kodai',   lastName: 'Senga',         throws: 'RIGHT', teamId: '121', era: 3.09, xERA: 3.21, fip: 3.14, whip: 1.04, hr9: 0.8,  flyBallPct: 26.7, hardContactPct: 29.4, barrelPct: 6.2, avgFastball: 95.8, hrVulnScore: 21 },
  { id: 'p-592662', name: 'Marcus Stroman',     firstName: 'Marcus',  lastName: 'Stroman',       throws: 'RIGHT', teamId: '112', era: 3.87, xERA: 4.12, fip: 3.94, whip: 1.22, hr9: 0.9,  flyBallPct: 28.1, hardContactPct: 33.4, barrelPct: 7.9, avgFastball: 91.7, hrVulnScore: 34 },
  { id: 'p-547874', name: 'Trevor Williams',    firstName: 'Trevor',  lastName: 'Williams',      throws: 'RIGHT', teamId: '120', era: 4.61, xERA: 4.98, fip: 4.74, whip: 1.38, hr9: 1.6,  flyBallPct: 44.1, hardContactPct: 46.2, barrelPct: 13.1, avgFastball: 90.8, hrVulnScore: 87 },
  { id: 'p-596130', name: 'Aaron Nola',         firstName: 'Aaron',   lastName: 'Nola',          throws: 'RIGHT', teamId: '143', era: 3.64, xERA: 3.78, fip: 3.71, whip: 1.14, hr9: 1.1,  flyBallPct: 36.2, hardContactPct: 38.1, barrelPct: 9.4, avgFastball: 91.8, hrVulnScore: 44 },
]

// ─── Seed Runner ──────────────────────────────────────────────────────────────

async function seed() {
  console.log('🌱 Seeding Nuke Tracker database...')

  // Stadiums
  console.log('⚾ Seeding 30 stadiums...')
  for (const s of STADIUMS) {
    await db.stadium.upsert({
      where: { id: s.id },
      create: s as any,
      update: {
        parkFactor: s.parkFactor,
        hrFactor: s.hrFactor,
        lhHrFactor: s.lhHrFactor,
        rhHrFactor: s.rhHrFactor,
      },
    })
  }

  // Teams (without stadiumId first to avoid FK issues)
  console.log('🏟  Seeding 30 teams...')
  for (const t of TEAMS) {
    await db.team.upsert({
      where: { abbreviation: t.abbreviation },
      create: {
        id: t.id,
        name: t.name,
        abbreviation: t.abbreviation,
        city: t.city,
        division: t.division,
        league: t.league,
        stadiumId: t.stadiumId,
      },
      update: {
        name: t.name,
        stadiumId: t.stadiumId,
      },
    })
  }

  // Pitchers
  console.log('⚡ Seeding pitchers...')
  for (const p of PITCHERS) {
    await db.pitcher.upsert({
      where: { id: p.id },
      create: p as any,
      update: {
        era: p.era,
        xERA: p.xERA,
        hr9: p.hr9,
        flyBallPct: p.flyBallPct,
        hardContactPct: p.hardContactPct,
        barrelPct: p.barrelPct,
        hrVulnScore: p.hrVulnScore,
      },
    })
  }

  console.log('✅ Seed complete!')
  console.log(`   Stadiums: ${STADIUMS.length}`)
  console.log(`   Teams:    ${TEAMS.length}`)
  console.log(`   Pitchers: ${PITCHERS.length}`)
}

seed()
  .catch((e) => { console.error('❌ Seed failed:', e); process.exit(1) })
  .finally(() => db.$disconnect())
